name: ci

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '!src/AzureApiUtils.psd1'
      - 'tests/**'
  workflow_dispatch:

jobs: 
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.AzureApiUtils_REPO }}

      - name: Install PowerShell dependencies
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer, platyPS -force

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path .\ -Settings PSGallery -Recurse -ReportSummary -Severity Error

      - name: Generate public help
        shell: pwsh
        run: |
          Remove-Module AzureApiUtils -Force -ErrorAction SilentlyContinue
          Import-Module .\src\AzureApiUtils.psd1
          Update-MarkdownHelpModule -Path 'docs' -RefreshModulePage -UpdateInputOutput -Force
          (Get-Content .\docs\AzureApiUtils.md) -replace '(.md\))', ')' | Out-File .\docs\AzureApiUtils.md -Force -Encoding ascii
          New-ExternalHelp -Path 'docs' -OutputPath 'en-us' -Force

      - name: Run Tests
        shell: pwsh
        run: |
          Install-Module Az.Accounts, Az.Resources -Force
          $config = New-PesterConfiguration -Hashtable @{ TestResult = @{ Enabled = $true }; Run = @{ Exit = $true }; CodeCoverage = @{ Enabled = $false; Path = @('src/public') } }
          Invoke-Pester -Configuration $config

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: Test-and-Coverage
          path: testResults.xml

      - name: Upload code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: Test-and-Coverage
          path: coverage.xml

      - name: Upload public help
        uses: LanceMcCarthy/Action-AzureBlobUpload@v2
        with:
          connection_string: ${{ secrets.STORAGE_CONNECTION_STRING }}
          container_name: help
          source_folder: en-us
          delete_if_exists: true
